package com.example.course_management.service;

import com.example.course_management.dto.UserDTO; // Assuming UserDTO exists
import com.example.course_management.entity.User;
import com.example.course_management.repository.UserRepository;
// Remove PasswordEncoder import if not using
// import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class AuthService {

    private final UserRepository userRepository;
    // Remove PasswordEncoder if not using
    // private final PasswordEncoder passwordEncoder;

    // Correct constructor
    public AuthService(UserRepository userRepository /*, PasswordEncoder passwordEncoder */) {
        this.userRepository = userRepository;
        // this.passwordEncoder = passwordEncoder;
    }

    // Keep existing register method (with plain text password as per user request)
    public User register(User user) {
        // No password encoding for now
        user.setActivated(true); // Or manage activation based on flow
        return userRepository.save(user);
    }

    /**
     * Creates a preliminary User record for an invited teacher.
     * The user is initially inactive and needs to complete registration using the token.
     * @param email The email address of the teacher to invite.
     * @param fullName The full name of the teacher.
     * @param token The registration token generated by the controller.
     * @return The saved User entity (without password, inactive).
     */
    public User createTeacherInvite(String email, String fullName, String token) {
        if (userRepository.existsByEmail(email)) {
            // Decide how to handle existing emails (e.g., error, update, ignore)
            // Throwing an error for now to prevent duplicates
            throw new RuntimeException("Email already exists: " + email);
        }

        User newUser = new User();
        newUser.setEmail(email);
        newUser.setFullName(fullName);
        // Set a default username or use email (ensure uniqueness if using username for login)
        newUser.setUsername(email); // Using email as username
        newUser.setRole("TEACHER"); // Assign TEACHER role
        newUser.setPassword(null); // No password set initially
        newUser.setRegistrationToken(token);
        newUser.setActivated(false); // User must complete registration

        return userRepository.save(newUser);
    }


    public UserDTO convertToDTO(User user) {
        // Ensure UserDTO constructor/setters match fields
        return new UserDTO(
                user.getId(),
                user.getUsername(),
                user.getRole(),
                user.getFullName(),
                user.getEmail()
        );
    }

    // Placeholder for future methods if needed:
    // public User findByRegistrationToken(String token) { ... }
    // public User completeTeacherRegistration(String token, String password) { ... }
}